const {
  VITE_URL_TRANSLATE,
  VITE_TRANSLATE_API_KEY,
  VITE_TRANSLATE_HOST,
  VITE_URL_DETECT_LANGUAGE,
  VITE_DETECT_LANGUAGE_API_KEY
} = import.meta.env

export {
  VITE_URL_TRANSLATE,
  VITE_TRANSLATE_API_KEY,
  VITE_TRANSLATE_HOST,
  VITE_URL_DETECT_LANGUAGE,
  VITE_DETECT_LANGUAGE_API_KEY
}
